name: PR mod validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed files
    steps:
      - uses: actions/checkout@v4
        with:
          # Fix: if the user's PR was not rebased or someone had pushed changes
          # to the target branch, the action would report files changed from the
          # PR commits and the target branch.
          # https://github.com/tj-actions/changed-files/discussions/2018
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Validate the changes
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          ADDED_FILES_COUNT: ${{ steps.changed-files.outputs.added_files_count }}
          MODIFIED_FILES_COUNT: ${{ steps.changed-files.outputs.modified_files_count }}
          ALL_CHANGED_AND_MODIFIED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          ALL_CHANGED_AND_MODIFIED_FILES_COUNT: ${{ steps.changed-files.outputs.all_changed_and_modified_files_count }}
        run: |
          python .github/pr_validation.py
