name: PR mod validation

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          # Fix: if the user's PR was not rebased or someone had pushed changes
          # to the target branch, the action would report files changed from the
          # PR commits and the target branch.
          # https://github.com/tj-actions/changed-files/discussions/2018
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Validate the changes
        run: |
          python .github/pr_validation.py --author ${{ github.actor }} ${{ steps.changed-files.outputs.all_changed_files }}
